In [1]:
import torch

a = torch.randn((2,3))
mask = torch.tensor([[1, 0, 0], [1, 1, 0]], dtype=torch.bool)
a[mask]


tensor([0.5113, 0.1161, 1.9593])

In [2]:
from vqtorch.nn import  VectorQuant
import torch
inplace_optimizer = lambda *args, **kwargs: torch.optim.SGD(*args, **kwargs, lr=50.0, momentum=0.9)
vq = VectorQuant(
            feature_size=5,     # feature dimension corresponding to the vectors
            num_codes=128,      # number of codebook vectors
            beta=1.0,           # (default: 0.9) commitment trade-off
            kmeans_init=False,    # (default: False) whether to use kmeans++ init
            norm='l2',           # (default: None) normalization for the input vectors
            cb_norm='l2',        # (default: None) normalization for codebook vectors
            affine_lr=10,      # (default: 0.0) lr scale for affine parameters
            sync_nu=0.2,         # (default: 0.0) codebook synchronization contribution
            replace_freq=20,     # (default: None) frequency to replace dead codes
            dim=-1,             # (default: -1) dimension to be quantized
            affine_groups=4,
            inplace_optimizer = inplace_optimizer
        )

input = torch.randn((2,3,5))
print(input)
mask = torch.tensor([[1,1,0],[1,0,0]])
output = vq(input)
print(output)


tensor([[[ 1.4293,  0.2757,  1.1454,  1.8593, -0.8667],
         [ 1.6642,  3.0250,  1.7501,  1.4711,  0.9272],
         [ 0.8729,  1.0004, -0.0467, -1.0041,  1.1359]],

        [[ 1.4677,  0.1872,  0.2534, -0.6242, -1.1886],
         [ 0.8304,  2.0559,  1.4685, -1.5476, -2.0512],
         [-0.7615,  0.9121,  0.6427, -0.6674, -0.3391]]])


(tensor([[[ 0.3743,  0.4454,  0.3602,  0.6185, -0.4680],
         [ 0.2449,  0.5615,  0.3658,  0.4873,  0.0032],
         [ 0.2762,  0.3889, -0.0027, -0.4235,  0.7718]],

        [[ 0.8530, -0.1201,  0.1973, -0.4193, -0.7342],
         [ 0.1142,  0.5106,  0.5380, -0.4353, -0.3449],
         [-0.2462,  0.4242,  0.3141, -0.4821,  0.0536]]],
       grad_fn=<PermuteBackward0>), {'z': tensor([[[[ 0.5171,  0.0997,  0.4144,  0.6727, -0.3136]],

         [[ 0.3922,  0.7129,  0.4124,  0.3467,  0.2185]],

         [[ 0.4330,  0.4963, -0.0232, -0.4981,  0.5635]]],


        [[[ 0.7288,  0.0929,  0.1258, -0.3099, -0.5902]],

         [[ 0.2245,  0.5559,  0.3971, -0.4185, -0.5547]],

         [[-0.4931,  0.5906,  0.4161, -0.4321, -0.2196]]]]), 'z_q': tensor([[[[ 0.3743,  0.4454,  0.3602,  0.6185, -0.4680]],

         [[ 0.2449,  0.5615,  0.3658,  0.4873,  0.0032]],

         [[ 0.2762,  0.3889, -0.0027, -0.4235,  0.7718]]],


        [[[ 0.8530, -0.1201,  0.1973, -0.4193, -0.7342]],

         [[ 0.