In [1]:
import torch

a = torch.randn((2,3))
mask = torch.tensor([[1, 0, 0], [1, 1, 0]], dtype=torch.bool)
a[mask]


tensor([0.5113, 0.1161, 1.9593])

In [2]:
from vqtorch.nn import  VectorQuant
import torch
inplace_optimizer = lambda *args, **kwargs: torch.optim.SGD(*args, **kwargs, lr=50.0, momentum=0.9)
vq = VectorQuant(
            feature_size=5,     # feature dimension corresponding to the vectors
            num_codes=128,      # number of codebook vectors
            beta=1.0,           # (default: 0.9) commitment trade-off
            kmeans_init=False,    # (default: False) whether to use kmeans++ init
            norm='l2',           # (default: None) normalization for the input vectors
            cb_norm='l2',        # (default: None) normalization for codebook vectors
            affine_lr=10,      # (default: 0.0) lr scale for affine parameters
            sync_nu=0.2,         # (default: 0.0) codebook synchronization contribution
            replace_freq=20,     # (default: None) frequency to replace dead codes
            dim=-1,             # (default: -1) dimension to be quantized
            affine_groups=4,
            inplace_optimizer = inplace_optimizer
        )

input = torch.randn((2,3,5))
print(input)
mask = torch.tensor([[1,1,0],[1,0,0]])
output = vq(input, mask)
print(output)


tensor([[[-0.7494,  0.1406, -0.3523,  0.2796, -0.4618],
         [ 0.2052,  0.3606, -0.9348, -0.5974,  0.4900],
         [ 2.7700,  0.0216, -1.9388,  0.0586,  0.6073]],

        [[ 2.1189,  1.2294, -0.2514, -0.4429, -0.2362],
         [ 0.5698,  1.2466, -1.0717,  0.8464, -1.4920],
         [-0.3821,  0.6153, -0.2265, -0.4393, -0.2794]]])
(tensor([[[-0.6033,  0.0134, -0.2445, -0.0824, -0.9429],
         [ 0.4384,  0.5902, -1.2939, -0.3002,  0.4658],
         [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000]],

        [[ 0.6710,  0.1496, -0.1850,  0.0094, -0.5892],
         [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000]]],
       grad_fn=<PermuteBackward0>), {'z': tensor([[[[-0.7506,  0.1408, -0.3529,  0.2800, -0.4625]],

         [[ 0.1601,  0.2813, -0.7293, -0.4661,  0.3823]],

         [[ 0.0000,  0.0000, -0.0000,  0.0000,  0.0000]]],


        [[[ 0.8431,  0.4892, -0.1000, -0.1762, -0.0940]],

         [[ 0.0000,  0.0000, -0.0000,  